# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scenario/nodes.proto
# Protobuf Python Version: 4.25.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14scenario/nodes.proto\x12\x08scenario\"6\n\x0bMessageNode\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04text\x18\x03 \x01(\t\"\x16\n\x08HTMLNode\x12\n\n\x02id\x18\x01 \x01(\x05\x42\rZ\x0bgo/scenariob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scenario.nodes_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013go/scenario'
  _globals['_MESSAGENODE']._serialized_start=34
  _globals['_MESSAGENODE']._serialized_end=88
  _globals['_HTMLNODE']._serialized_start=90
  _globals['_HTMLNODE']._serialized_end=112
# @@protoc_insertion_point(module_scope)
